"""add performance indexes on lead_id, status, due_date columns

Revision ID: 6f2de76f8e8c
Revises: d15bbd0c4acc
Create Date: 2026-08-25 14:21:57.936509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2de76f8e8c'
down_revision: Union[str, None] = 'd15bbd0c4acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_calls_lead_id'), 'calls', ['lead_id'], unique=False)
    op.create_index(op.f('ix_crm_stage_history_lead_id'), 'crm_stage_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_analysis_lead_id'), 'lead_analysis', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_qualification_lead_id'), 'lead_qualification', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_sources_lead_id'), 'lead_sources', ['lead_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_service_recommendations_lead_id'), 'service_recommendations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_lead_id'), 'tasks', ['lead_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_lead_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_service_recommendations_lead_id'), table_name='service_recommendations')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_lead_sources_lead_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_qualification_lead_id'), table_name='lead_qualification')
    op.drop_index(op.f('ix_lead_analysis_lead_id'), table_name='lead_analysis')
    op.drop_index(op.f('ix_crm_stage_history_lead_id'), table_name='crm_stage_history')
    op.drop_index(op.f('ix_calls_lead_id'), table_name='calls')
    # ### end Alembic commands ###
