"""add search_configurations table

Revision ID: 8b43d9ba9cd5
Revises: bd3981e95523
Create Date: 2026-08-25 02:50:27.884765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b43d9ba9cd5'
down_revision: Union[str, None] = 'bd3981e95523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lead_search_runs', sa.Column('search_configuration_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lead_search_runs', 'search_configurations', ['search_configuration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_search_runs', type_='foreignkey')
    op.drop_column('lead_search_runs', 'search_configuration_id')
    op.drop_table('search_configurations')
    # ### end Alembic commands ###
