"""add qualification_rules and lead_qualification tables

Revision ID: 9e3ce2415e15
Revises: 8b43d9ba9cd5
Create Date: 2026-08-25 03:36:39.922713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3ce2415e15'
down_revision: Union[str, None] = '8b43d9ba9cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_qualification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('passed_rules', sa.JSON(), nullable=False),
    sa.Column('failed_rules', sa.JSON(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('previous_result', sa.String(length=20), nullable=True),
    sa.Column('override_reason', sa.String(length=1000), nullable=True),
    sa.Column('overridden_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_qualification')
    op.drop_table('qualification_rules')
    # ### end Alembic commands ###
