"""add schedule and last_run_at to campaigns

Revision ID: af6078c3a3d0
Revises: 6f2de76f8e8c
Create Date: 2026-08-27 00:43:32.683024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6078c3a3d0'
down_revision: Union[str, None] = '6f2de76f8e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('schedule', sa.String(length=20), nullable=True))
    op.add_column('campaigns', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'last_run_at')
    op.drop_column('campaigns', 'schedule')
    # ### end Alembic commands ###
