"""add reply classification fields to messages

Revision ID: cccf1bee508f
Revises: 6e473daf1026
Create Date: 2026-08-25 12:51:05.202381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccf1bee508f'
down_revision: Union[str, None] = '6e473daf1026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('from_email', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('messages', sa.Column('classification_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('messages', sa.Column('classification_summary', sa.String(length=1000), nullable=True))
    op.add_column('messages', sa.Column('suggested_action', sa.String(length=1000), nullable=True))
    op.add_column('messages', sa.Column('review_required', sa.Boolean(), nullable=False))
    op.alter_column('messages', 'to_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'to_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('messages', 'review_required')
    op.drop_column('messages', 'suggested_action')
    op.drop_column('messages', 'classification_summary')
    op.drop_column('messages', 'classification_confidence')
    op.drop_column('messages', 'category')
    op.drop_column('messages', 'from_email')
    # ### end Alembic commands ###
