"""add calls table and lead contact_name

Revision ID: e8e3b0cf671f
Revises: cccf1bee508f
Create Date: 2026-08-25 13:04:31.371190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e3b0cf671f'
down_revision: Union[str, None] = 'cccf1bee508f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('reason_for_calling', sa.String(length=1000), nullable=True),
    sa.Column('call_objective', sa.String(length=1000), nullable=True),
    sa.Column('script', sa.String(length=4000), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leads', sa.Column('contact_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'contact_name')
    op.drop_table('calls')
    # ### end Alembic commands ###
